Connects to #104. PASS1A data embargo extension.
MoTrPAC/motrpac-frontend pull request #107
Opened 2021-01-11 20:30 UTC by jimmyzhen

### Key Changes:

1. Updated embargo extension language on **Data Access** page.
2. Added embargo extension entry on **Announcements** page.
3. Added embargo extension alert UI only visible to external users on **Dashboard** page.
4. Added embargo extension alert UI only visible to external users on **Releases** page.

### Steps to test:

1. Without signing in on the data hub portal, navigate to `^/data-access` and expect to see an updated embargo language (in **bold**).
2. Then navigate to `^/announcements` and expect to see a new entry titled **"Embargo extension"**.
3. Sign in as an external user and expect to see an alert UI pertinent to the embargo extension message on the _Dashboard_.
4. Then navigate to `^/releases` and expect to see an alert UI pertinent to the embargo extension message.
5. Sign out and then sign in again as an internal user. Verify the absence of the alert UIs on the 2 pages described above.

2021-01-11 20:58 UTC, cteng585 reviewed
Alert behavior is as described (alerts are present for external users but not internal users, bolded portion on the data access page is present).

With regards to the text that is used, for the portion:
> Until then, data can only be used for analyses supporting grant submissions, and not be used in abstracts, manuscripts, preprints or presentations.

I feel that the second part of the sentence is a little awkward and might read better as (bolded part for the change):
> Until then, data can only be used for analyses supporting grant submissions, and **cannot** be used in abstracts, manuscripts, preprints or presentations.

Also on the data access page:
> Please note that there is a publication embargo on the MoTrPAC data until the release of additional control data necessary to fully control the analysis for molecular changes due to e.g. sampling and fasting time post exercise.

I like the wording that was used in other places better:
> Please note that the publication embargo on MoTrPAC data has been extended until release of additional control data necessary to fully control for non-exercise induced molecular changes in the current dataset (**e.g. sampling and fasting time post exercise**).

2021-01-11 21:08 UTC, jimmyzhen commented
@cteng585, in regards to your suggested changes to the language, would you mind comment the shared Google Doc and request Malene for input? It will be preferable if we can keep it all in one place. Thanks.

2021-01-11 22:04 UTC, ysyskim4 requested changes
On the data-access page, 'Data Use Agreement' section also has the embargo text as below. Do we keep the text? or should we update it?
- The embargo period for any type of publication of MoTrPAC External Release 1 data is 15 months after external release 1: through January 15, 2021.

2021-01-12 14:49 UTC, jimmyzhen commented
Thank, Young. Great catch!

The requested changes had been addressed with newer commits. Please review again.

2021-01-12 17:40 UTC, ysyskim4 approved these changes
looks great.

2021-01-12 18:43 UTC, cteng585 approved these changes
Thanks for implementing the text changes. Everything looks good now!

2021-01-13 02:08 UTC, kilodalton commented
PR also addresses Dependabot CVE-2020-28168 axios vulnerability

2021-01-13 02:12 UTC, merged